package main

import (
	"fmt"
	"path/filepath"
	"strings"

	fooddelivery "github.com/stablekernel/crucible/examples/fooddelivery"
	"github.com/stablekernel/crucible/state"
)

// diagramSpec describes one generated Mermaid partial: a real machine rendered
// via its ToMermaid method, written as a fenced ```mermaid block that the
// astro-mermaid integration renders client-side. slug is the output filename
// stem; title and caption document what the diagram shows.
type diagramSpec struct {
	slug    string
	title   string
	caption string
	build   func() (string, error)
}

// diagramSpecs enumerates the machines diagrammed into the _generated section.
// The flagship order machine is the primary artifact (it exercises hierarchy,
// parallel regions, guards, timers, and final states in one graph); the
// access-gate machine is a compact second example focused on a single guarded
// transition for pages that want a minimal diagram.
var diagramSpecs = []diagramSpec{
	{
		slug:    "fooddelivery-order",
		title:   "Food-delivery order lifecycle",
		caption: "The flagship order machine: hierarchical fulfillment, a parallel watchdog region, a registry-bound guard, and timer-driven escalation.",
		build:   buildOrderDiagram,
	},
	{
		slug:    "access-gate",
		title:   "Guarded access gate",
		caption: "A compact machine demonstrating a named guard on a transition plus a compound state.",
		build:   buildAccessGateDiagram,
	},
}

// generateDiagrams renders each machine's Mermaid source into a partial under
// <contentRoot>/_generated/diagrams/ and returns the absolute paths written, in
// deterministic order. Each ToMermaid call is a pure function of the machine
// graph, so output is byte-identical across runs.
func generateDiagrams(contentRoot string) ([]string, error) {
	outDir := filepath.Join(contentRoot, "_generated", "diagrams")
	written := make([]string, 0, len(diagramSpecs))
	for _, spec := range diagramSpecs {
		mermaid, err := spec.build()
		if err != nil {
			return nil, fmt.Errorf("build diagram %q: %w", spec.slug, err)
		}
		// Underscore-prefix the filename so Starlight's content loader (glob
		// pattern **/[^_]*) excludes these partials from routing: they are
		// embedded into pages, not standalone routes, so they carry no Starlight
		// frontmatter and must not be treated as collection entries.
		outPath := filepath.Join(outDir, "_"+spec.slug+".md")
		if err := writeGenerated(outPath, diagramPartial(spec, mermaid)); err != nil {
			return nil, err
		}
		written = append(written, outPath)
	}
	return written, nil
}

// diagramPartial wraps one machine's Mermaid source as a Markdown partial:
// frontmatter is omitted because these files are embedded into example/concept
// pages rather than rendered as standalone routes. A leading HTML comment marks
// the file as generated. The Mermaid body is emitted verbatim inside a fenced
// block so astro-mermaid transforms it into a rendered diagram.
func diagramPartial(spec diagramSpec, mermaid string) string {
	var b strings.Builder
	b.WriteString("<!-- Generated by tools/docsgen from a live example machine. Do not edit. -->\n\n")
	b.WriteString("```mermaid\n")
	b.WriteString(strings.TrimRight(mermaid, "\n"))
	b.WriteString("\n```\n")
	return b.String()
}

// buildOrderDiagram forges the flagship food-delivery order machine via the
// example's own NewModel constructor and renders it to Mermaid. Reusing the
// example guarantees the diagram tracks the real, tested machine rather than a
// docs-only copy.
func buildOrderDiagram() (string, error) {
	m, err := fooddelivery.NewModel()
	if err != nil {
		return "", fmt.Errorf("forge order model: %w", err)
	}
	return m.ToMermaid(), nil
}

// gateStage and gateSignal are the access-gate example machine's state and
// event alphabets.
type (
	gateStage  string
	gateSignal string
)

const (
	gateLocked    gateStage  = "Locked"
	gateAuthing   gateStage  = "Authenticating"
	gateChecking  gateStage  = "Checking"
	gateGranted   gateStage  = "Granting"
	gateOpen      gateStage  = "Open"
	gateDenied    gateStage  = "Denied"
	gateInsertID  gateSignal = "InsertBadge"
	gateValidated gateSignal = "Validated"
	gateRejected  gateSignal = "Rejected"
)

// gateCtx is the access-gate machine's context: a single flag the guard reads.
type gateCtx struct {
	Authorized bool
}

// buildAccessGateDiagram forges a compact machine that exercises a named guard
// on a transition and a compound (super/sub) state, then renders it to Mermaid.
// It is intentionally small so pages wanting a minimal diagram have one that
// still demonstrates real Crucible features.
func buildAccessGateDiagram() (string, error) {
	m := state.Forge[gateStage, gateSignal, gateCtx]("access-gate").
		Guard("authorized", func(g state.GuardCtx[gateCtx]) bool { return g.Entity.Authorized }).
		State(gateLocked).
		SuperState(gateAuthing).
		SubState(gateChecking).
		SubState(gateGranted).Final().
		Initial(gateChecking).
		Transition(gateChecking).On(gateValidated).When("authorized").GoTo(gateGranted).
		EndSuperState().
		State(gateOpen).Final().
		State(gateDenied).Final().
		Initial(gateLocked).
		Transition(gateLocked).On(gateInsertID).GoTo(gateAuthing).
		Transition(gateAuthing).On(gateValidated).When("authorized").GoTo(gateOpen).
		Transition(gateAuthing).On(gateRejected).GoTo(gateDenied).
		Quench()

	return m.ToMermaid(), nil
}
