// SPDX-License-Identifier: Apache-2.0

package main

import "testing"

// TestNormalizeGodoc covers the regex post-processing that turns raw gomarkdoc
// output into a Starlight-ready page body: the DO NOT EDIT banner is dropped,
// the duplicate package-name H1 is removed (the frontmatter title becomes the
// page heading), git-derived source links are stripped for determinism,
// cosmetic backslash-escaping is collapsed, and surrounding blank lines are
// trimmed. The title argument is unused today and passed through unchanged, so
// the cases vary only the raw body.
func TestNormalizeGodoc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		raw  string
		want string
	}{
		{
			name: "drops do-not-edit banner and leading blank lines",
			raw:  "<!-- Code generated by gomarkdoc. DO NOT EDIT -->\n\nBody text.",
			want: "Body text.\n",
		},
		{
			name: "removes the leading package H1",
			raw:  "# state\n\nThe kernel.",
			want: "The kernel.\n",
		},
		{
			name: "banner then H1 both removed",
			raw:  "<!-- Code generated by gomarkdoc. DO NOT EDIT -->\n# sink\n\nFan-out.",
			want: "Fan-out.\n",
		},
		{
			name: "strips a gomarkdoc view-source link",
			raw:  "Doc line [](<https://github.com/stablekernel/crucible/blob/abc123/state/kernel.go#L10>) trailing.",
			want: "Doc line trailing.\n",
		},
		{
			name: "unescapes cosmetic body punctuation escapes",
			raw:  "Forge\\(\\) builds a machine \\- the entry point\\.",
			want: "Forge() builds a machine - the entry point.\n",
		},
		{
			name: "collapses a double-escaped dash inside a heading to plain text",
			raw:  "## Forge \\\\\\- entry\n\nbody",
			want: "## Forge - entry\n\nbody\n",
		},
		{
			name: "leaves load-bearing inline markdown escapes in body intact",
			// A backslash before * or _ carries emphasis meaning, so the body pass
			// must not touch it.
			raw:  "Use \\*literal\\* not emphasis.",
			want: "Use \\*literal\\* not emphasis.\n",
		},
		{
			name: "trims trailing whitespace and guarantees a single trailing newline",
			raw:  "Just a line.\n\n\n",
			want: "Just a line.\n",
		},
		{
			name: "empty input yields a lone newline",
			raw:  "",
			want: "\n",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := normalizeGodoc(tc.raw, "ignored-title"); got != tc.want {
				t.Fatalf("normalizeGodoc(%q) = %q, want %q", tc.raw, got, tc.want)
			}
		})
	}
}

// TestUnescapeGodoc covers the two-pass unescaper directly: every escaped
// punctuation character in a heading line is unescaped (godoc headings are
// plain text), while body text is unescaped only before punctuation with no
// inline-Markdown meaning, so emphasis, links, code, and table escapes survive.
func TestUnescapeGodoc(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "heading unescapes all punctuation including markdown-significant chars",
			in:   "### A \\* B \\_ C \\[ D",
			want: "### A * B _ C [ D",
		},
		{
			name: "body keeps emphasis and link escapes, drops cosmetic ones",
			in:   "keep \\* and \\[ but drop \\( and \\,",
			want: "keep \\* and \\[ but drop ( and ,",
		},
		{
			name: "heading double-escape collapses fully",
			in:   "# title \\\\\\.",
			want: "# title .",
		},
		{
			name: "no escapes is a no-op",
			in:   "plain heading\nand body",
			want: "plain heading\nand body",
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := unescapeGodoc(tc.in); got != tc.want {
				t.Fatalf("unescapeGodoc(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// TestCollapseEscapes covers the fixed-point reducer used by both unescape
// passes: it applies the matcher repeatedly until the text stops changing, so a
// chain of backslashes before a target character collapses to the bare
// character in one call.
func TestCollapseEscapes(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   string
		want string
	}{
		{name: "single escape", in: `a\-b`, want: "a-b"},
		{name: "double escape collapses fully", in: `a\\-b`, want: "a-b"},
		{name: "triple escape collapses fully", in: `a\\\-b`, want: "a-b"},
		{name: "unrelated backslash untouched", in: `a\*b`, want: `a\*b`},
		{name: "no backslash", in: "ab", want: "ab"},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := collapseEscapes(tc.in, godocBodyEscape); got != tc.want {
				t.Fatalf("collapseEscapes(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}

// TestYAMLString covers the double-quoted YAML scalar rendering used for
// frontmatter values: backslash and double-quote are the only two characters
// that need escaping inside a double-quoted scalar, and the result is always
// wrapped in quotes so indicator characters (a leading colon, symbol, etc.)
// parse as a single string rather than as a mapping.
func TestYAMLString(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   string
		want string
	}{
		{name: "plain text is quoted", in: "hello world", want: `"hello world"`},
		{name: "value with a colon stays a single scalar", in: "a: b", want: `"a: b"`},
		{name: "double quotes are escaped", in: `say "hi"`, want: `"say \"hi\""`},
		{name: "backslashes are escaped", in: `a\b`, want: `"a\\b"`},
		{
			name: "backslash before quote escapes both, in source order",
			in:   `a\"b`,
			want: `"a\\\"b"`,
		},
		{name: "empty string is an empty quoted scalar", in: "", want: `""`},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			if got := yamlString(tc.in); got != tc.want {
				t.Fatalf("yamlString(%q) = %q, want %q", tc.in, got, tc.want)
			}
		})
	}
}
